### ISSUE TITLE
License and contribution?

### ISSUE THREAD

**Issue by Kunde21** [minio/asm2plan9s#1]
Is there a plan to open this tool to public contribution?  I have some suggestions/improvements on my fork that I'd like to offer back, but there's no guidelines with respect to licensing/contribution.

**Comment by harshavardhana** [comment]
Licensing is Apache 2.0.

**Comment by fwessels** [comment]
No specific plan but if you submit a PR we would be happy to look at it.

**Comment by harshavardhana** [comment]
Closing this issue as stale @Kunde21 if you have suggestions/improvements feel free to submit a PR.
