### ISSUE TITLE
Use go1.10's native SIMD instructions up to AVX2? (amd64)

### ISSUE THREAD

**Issue by knweiss** [minio/asm2plan9s#5]
According to the [go1.10 release notes](https://golang.org/doc/go1.10) Go now supports SIMD instructions up to AVX2 natively:

> For the X86 64-bit port, the assembler now supports 359 new instructions, including the full AVX, AVX2, BMI, BMI2, F16C, FMA3, SSE2, SSE3, SSSE3, SSE4.1, and SSE4.2 extension sets.

So I'm wondering if `asm2plan9s` should/could remove the instruction comments consisting of these (now supported) instructions and replace them with native Go assembly instructions **where possible** (instead of generating BYTE sequences)? This would make the Go assembly source code more readable and reduce the instruction comments to a minimum as they would only be used when necessary.

(I haven't used `asm2plan9s` myself yet. I've just casually read the first time about this project and this question came up. I'm sorry if it doesn't make sense.)

**Comment by fwessels** [comment]
That is not as simple as it sounds due to the different syntax between eg. the Intel assembly syntax and the Plan 9 syntax. 

As such this is up to the developer to do the conversion (and make sure it is the intended behavior).
