### ISSUE TITLE
trying to use with lzfse

### ISSUE THREAD

**Issue by blacktop** [minio/asm2plan9s#7]
Hello,

I'm trying to gen go asm for the [lzfse](https://github.com/lzfse/lzfse) project and failing spectacularly.  I primarily just want to exercise the `lzfse_decode_buffer` function so I thought I would just need to (in lzfse):

```bash
$ mkdir build
$ cd build
$ cmake ..
$ make src/lzfse_decode.c.s
```

Then create the following Go file:

```go
//+build !noasm
//+build !appengine

package lzfse

import (
	"unsafe"
)

//go:noescape
func _lzfse_decode_buffer(dstBuffer unsafe.Pointer, dstSize uint64, srcBuffer unsafe.Pointer, srcSize uint64, scratchBuffer unsafe.Pointer)

//go:noescape
func _lzfse_decode_scratch_size() uint64

func lzfse_decode_buffer(srcBuffer []byte) []byte {

	dstBuffer := make([]byte, 4*len(srcBuffer))
	scratchBuffer := make([]byte, lzfse_decode_scratch_size())
	_lzfse_decode_buffer(unsafe.Pointer(&dstBuffer), uint64(len(dstBuffer)), unsafe.Pointer(&dstBuffer), uint64(len(dstBuffer)), unsafe.Pointer(&scratchBuffer))

	return dstBuffer
}

func lzfse_decode_scratch_size() uint64 {
	return _lzfse_decode_scratch_size()
}
```

And finally run this (however):

```bash
$ ❯ c2goasm -a lzfse_decode.c.s lzfse_decode_amd64.s
Processing lzfse_decode.c.s
panic: Failed to find function prototype for _lzfse_decode_scratch_size

goroutine 1 [running]:
main.parseCompanionFile(0xc00001b140, 0x15, 0xc000020429, 0x1a, 0x0, 0x0, 0x20300000000000, 0x15fffff, 0x400, 0x1406600)
        /Users/blacktop/go/src/github.com/minio/c2goasm/arguments.go:75 +0x22b
main.process(0xc0000ce000, 0xaa, 0x100, 0xc00001b140, 0x15, 0x0, 0x0, 0x0, 0xc00000c7e0, 0x0)
        /Users/blacktop/go/src/github.com/minio/c2goasm/c2goasm.go:87 +0x1e0
main.main()
        /Users/blacktop/go/src/github.com/minio/c2goasm/c2goasm.go:265 +0x3da
``` 

I apologize as I know these kinds of "issues" aren't fun to help with, and I appreciate ANY help or guidance you can offer.  Also I'm not sure if this issue belongs on this repo or the `c2goasm` repo, however, the issues have been disabled on that repo, most likely to stop issues like **this** one from being created 😬

**Comment by eriklupander** [comment]
I ran into the same issue with c2goasm (on OS X) when I had compiled my C snippet (the MultiplyAndAdd example) using:

```
clang -c -S -march=native -masm=intel -mno-red-zone -mstackrealign -mllvm -inline-threshold=1000 -fno-asynchronous-unwind-tables -fno-exceptions -fno-rtti <my source file.c>
```

When I used:

```
c++ -c -O3 -mavx -mfma -masm=intel -fno-asynchronous-unwind-tables -fno-exceptions -fno-rtti -S MultiplyAndAdd.c
```

it worked. 

I debugged the c2goasm code and found out that it seemed as the `clang` assembly generation had created a `_MultiplyAndAdd: ` label  (note the leading underscore), which made the match `if match[1] == "_"+protoName {` at line 85 in `arguments.go` try to find a func with double leading underscores, e.g. `__MultiplyAndAdd`. If I simply removed that `"_"+` it worked for me.

Problably not a proper fix, but my best guess (I'm no assembly guy) is that how your assembly is generated by the C/C++ compiler matters. Hope this helps.
